version: '3.8'

volumes:
  memo-database-volume:
    name: memo-database-volume

networks:
  memo-network:
    name: memo-network
    driver: bridge

services:

  conventional-commit-nodejs:
    image: conventional-commit-nodejs
    build: nodejs
    working_dir: /var/www/app
    volumes:
      - ../:/var/www/app
    networks:
      - memo-network

  memo-db:
    image: mariadb:10.6
    hostname: maria
    volumes:
      - memo-database-volume:/var/lib/mysql
      - ./data/db:/docker-entrypoint-initdb.d
#      - ./data/db/sql-schema.sql:/sql-schema.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=memo_db
    networks:
      - memo-network
